server:
  shutdown: graceful
  port: 8080

spring:
  thymeleaf:
    cache: false
  data:
    mongodb:
      uri: mongodb://hzn:hzn@localhost:27017/hzn-framework?minPoolSize=1&maxPoolSize=10
      auto-index-creation: true

allowed:
  origins: "*"
